# Generated by Django 5.2.7 on 2025-11-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Animais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('entrevista_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_field', models.DateField(db_column='data_')),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'entrevista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtapaRelacao',
            fields=[
                ('etapa_relacao_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Etapa_Relacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('etapa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Etapas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('processo_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_field', models.CharField(db_column='status_', max_length=255)),
            ],
            options={
                'db_table': 'Processo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessoEtapa',
            fields=[
                ('processo_etapa_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_field', models.CharField(db_column='status_', max_length=255)),
            ],
            options={
                'db_table': 'Processo_Etapa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recusa',
            fields=[
                ('recusa_id', models.AutoField(primary_key=True, serialize=False)),
                ('justificativa', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'recusa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('solicitacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=255)),
                ('comprovante_residencia', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Tipo_Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('senha', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Validacao',
            fields=[
                ('validacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'validacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitacao',
            fields=[
                ('visitacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_field', models.DateField(db_column='data_')),
                ('endereco', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'visitacao',
                'managed': False,
            },
        ),
    ]
